### PR TITLE
updated neuro tissue types

### PR DESCRIPTION
**Pull request by blogsdon**

### CODE REVIEW

**Comment by kdaily** [comment]
Check if these are MeSH terms.

**Comment by blogsdon** [comment]
these terms are _**not**_ in mesh:

frontal pole
occipital visual cortex
inferior temporal gyrus
middle temporal gyrus
temporal pole
superior parietal lobe

**Comment by kdaily** [comment]
Is 'frontal pole' the same as 'frontal lobe'?

https://meshb.nlm.nih.gov/#/record/ui?ui=D005625

**Comment by kdaily** [comment]
Some of these are in the BRCT (Brain Region and Cell Type) ontology. I would consider that a suitable reference as well:

http://bioportal.bioontology.org/ontologies/BRCT/?p=classes&conceptid=http%3A%2F%2Fwww.semanticweb.org%2Fontologies%2F2009%2F9%2FOntology1255357986125.owl%23Inferior_temporal_gyrus&jump_to_nav=true

**Pull request merged**
