### PR TITLE
Add Infinium Omni2.5Exome-8 v1.3 to platform

### PR DESCRIPTION
**Pull request by karawoo**

### CODE REVIEW

**Comment by cw-dvr8** [comment]
@karawoo The "platform" key is one of the ones on my list that currently doesn't have a description.  Do you feel like you can add one while you're in there, or should it be its own pull request?

**Comment by karawoo** [comment]
Sure, I've added one. Does adding a source as well (per #301) interfere with anything you are doing, @cw-dvr8?

**Comment by cw-dvr8** [comment]
Not at all, it's actually helpful.

**Comment by karawoo** [comment]
hmm, it might be good to be specific in case there are differences between versions that affect the outputs? but i'm open to making it more general

**Comment by karawoo** [comment]
@kelshmo can you confirm whether you're ok with the more specific term?

**Comment by kelshmo** [comment]
I'm fine with a specific term.

**Pull request merged**
