### PR TITLE
Update individualIdSource.json

### PR DESCRIPTION
**Pull request by kelshmo**
This PR adds two terms relevant to PEC. I followed our new standards for alphabetical ordering.

### CODE REVIEW

**Review by cw-dvr8 — CHANGES_REQUESTED** [review]
For annotation schemas, you also need to increment the version number in the "$id" statement or it will fail the checks.  In this case you want to change

sage.annotations-experimentalData.individualIdSource-0.0.6

to

sage.annotations-experimentalData.individualIdSource-0.0.7

I forget to do this a lot.

**Comment by kelshmo** [comment]
@cw-dvr8 Ok, what about the statement in "$schema" where draft-07 is noted?

**Comment by cw-dvr8** [comment]
@kelshmo "draft-07" stays the same.

**Review by cw-dvr8 — APPROVED** [review]
Looks good.  In the future either Abby or Nicole can review these until you and Juliane get comfortable with the process.

**Review by avanlinden — APPROVED** [review]

**Review by Aryllen — APPROVED** [review]

**Pull request merged**
