### PR TITLE
Update neuro.json

### PR DESCRIPTION
**Pull request by kelshmo**
Removed group key because no longer in use.

### CODE REVIEW

**Comment by karawoo** [comment]
@kdaily @amapeters can you confirm that we're not using this key across any neuro projects? I don't think I am using it.

**Comment by kdaily** [comment]
We use it in BSMN. The groups involved have not been added to this key, though.

**Comment by karawoo** [comment]
Maybe we should keep the key and add a description but remove the enumerated values and just let it be any string?

**Comment by kdaily** [comment]
@karawoo I like the proposal!

**Comment by kdaily** [comment]
See #422.

**Comment by kelshmo** [comment]
No objections! This initial request to remove the key back in September came out of a conversation with Yooree.

**Comment by kdaily** [comment]
OK! I'm going to close this and I'll make a new request that does what is proposed above. Thanks @kelshmo @karawoo!

**Pull request closed without merging**
