### PR TITLE
Add familialRelationship

### PR DESCRIPTION
**Pull request by cw-dvr8**

### CODE REVIEW

**Review by karawoo — COMMENTED** [review]
I like that "son" specifies that it's a human but "father" does not...

Should we consider adding other relationships besides father/son as well?

**Comment by cw-dvr8** [comment]
These were the only two we required, but I can add "mother" and "daughter" as well.  I would hesitate to add any more than that until they become necessary.

**Comment by karawoo** [comment]
If we do add more I think we should include gender neutral options (parent/child)

**Comment by cw-dvr8** [comment]
The definitions of "child" that I found referenced a specific age group instead of a family relationship.  I added "offspring" instead.

**Review by karawoo — APPROVED** [review]
Thanks for the updates! Glad that github actions caught the syntax issue too.

**Pull request merged**
