### PR TITLE
Added values to tissue

### PR DESCRIPTION
**Pull request by ychae**
medial orbital frontal cortex
medial prefrontal cortex
medial dorsal nucleus of thalamus
inferior temporal cortex
posterior inferior parietal cortex

### CODE REVIEW

**Comment by ychae** [comment]
Hi all, thoughts on `mediodorsal nucleus of thalamus` vs `medial dorsal nucleus of thalamus`?

**Comment by kkdang** [comment]
Mette will check what is done in Brain span data.

**Comment by kdaily** [comment]
@amapeters did you check per @kkdang's request?

**Comment by kdaily** [comment]
@ychae can you manage w/ help from @amapeters? Thanks!

**Comment by ychae** [comment]
Yep, can do!

**Comment by ychae** [comment]
Searching OLS for `mediodorsal nucleus of thalamus` results in `medial dorsal nucleus of thalamus`. Since only 10 files in PEC are using the term `mediodorsal nucleus of thalamus`, I've updated them to `medial` and am removing `medio` from the annotation terms.

**Pull request merged**
