### PR TITLE
Additional individualIDSources for PEC

### PR DESCRIPTION
**Pull request by amapeters**

### CODE REVIEW

**Comment by Aryllen** [comment]
This is out of date with the new changes to the repo (for example, this is in a folder called 'data' whereas this should be in a main folder called 'terms' and the correct subfolder). @cw-dvr8 and @amapeters, it might be simpler to close this issue and start a new one using the current version of the file.

**Comment by cw-dvr8** [comment]
@Aryllen I agree.

**Comment by amapeters** [comment]
@Aryllen agree as well

**Comment by amapeters** [comment]
@cw-dvr8 can you make these changes

**Pull request closed without merging**
