### PR TITLE
Add NCX NES to tissue

### PR DESCRIPTION
**Pull request by cw-dvr8**

### CODE REVIEW

**Comment by avanlinden** [comment]
If these are stem cells, should this be under cellType rather than tissue?

**Comment by cw-dvr8** [comment]
Possibly, but they're listed under a brain region in a PEC study so I need them added to tissue.

**Comment by Aryllen** [comment]
@cw-dvr8, would it possible to list the respective tissue for the brain region and then include cellType to drill down to these stem cells? It seems odd to have a specific cell type in tissue.

**Comment by cw-dvr8** [comment]
@Aryllen No, NCX NES is what's listed as the tissue.

**Comment by cw-dvr8** [comment]
However, I can add cellType and just leave tissue blank for this one.  That's probably the better solution.  Will close this and open one for cellType.

**Pull request closed without merging**
