### PR TITLE
added transcriptNormalizationMethod key and fpkm, TMM values

### PR DESCRIPTION
**Pull request by ychae**

### CODE REVIEW

**Comment by kdaily** [comment]
Has conflicts due to file renaming, please resolve!

**Comment by kdaily** [comment]
@ychae Has conflict - probably due to existing before the big move. please fix or close!

**Comment by kdaily** [comment]
open an issue that tracks the changes you want here, and then please close this PR. Thanks!

**Comment by ychae** [comment]
See issue #330

**Pull request closed without merging**
