### PR TITLE
Added neural progenitor cell

### PR DESCRIPTION
**Pull request by pitviper6**

### CODE REVIEW

**Review by kelshmo — APPROVED** [review]

**Comment by pitviper6** [comment]
Hmm, not sure why this is failing.

**Comment by kelshmo** [comment]
It looks like [this reference](https://github.com/Sage-Bionetworks/synapseAnnotations/blob/master/terms/experimentalData/reprogrammedCellType.json#L7) needs to also be incremented to 0.0.6

**Review by Aryllen — APPROVED** [review]

**Review by Aryllen — CHANGES_REQUESTED** [review]
Whoops, approved, but I see the issue. The reprogrammedCellType and cellType issue rears it's ugly head, again. Since they both have to be updated in the same PR, I will help out and fix the issue on this branch and close the other PR.

**Review by Aryllen — APPROVED** [review]
The current failure is due to cellType not being registered, yet.

**Pull request merged**
