### PR TITLE
Added platform = Q-Exactive Plus

### PR DESCRIPTION
**Pull request by amapeters**

### CODE REVIEW

**Comment by karawoo** [comment]
@amapeters would this source work instead? http://purl.obolibrary.org/obo/MS_1002634

**Comment by amapeters** [comment]
Yes, that better than the manufacturer link

**Comment by amapeters** [comment]
Can you also change the link for the 'orbitrap fusion" to this http://www.ontobee.org/ontology/MS?iri=http://purl.obolibrary.org/obo/MS_1002416

**Comment by karawoo** [comment]
I've updated the source. Both the manufacturer link and the new source list it as "Q Exactive Plus" (no hyphen), so I updated that as well.

**Pull request merged**
