### PR TITLE
Added script to download GEO annotations

### PR DESCRIPTION
**Pull request by bswhite**
I've added a script get-geo-annotations.R to pull annotations from GEO.  

Thanks,
Brian

### CODE REVIEW

**Comment by bswhite** [comment]
Once I get permission to preview HTML in Synapse, an R markdown demo involving this script will be at:
https://www.synapse.org/#!Synapse:syn7444884/wiki/449472

**Comment by bswhite** [comment]
OK.  The R markdown demo should now be viewable:
https://www.synapse.org/#!Synapse:syn7444884/wiki/449472

**Comment by sgosline** [comment]
@bswhite Can you please remove this pr and commit to the annotation utilities repo?

**Comment by kdaily** [comment]
Close - please move to it's own package, or possibly the `synAnnotationUtils` package (though that is Python).

Another option to have it versioned and publicly available without making a package is [Gist](https:gist.github.com).

**Pull request closed without merging**
