### PR TITLE
Ncx nes cell type

### PR DESCRIPTION
**Pull request by cw-dvr8**

### CODE REVIEW

**Comment by cw-dvr8** [comment]
@Aryllen This is failing because of the connection with reprogrammedCellType.  What do we need to do to resolve it?

**Comment by Aryllen** [comment]
@cw-dvr8, update reprogrammedCellType to reference your new version of cellType. So reprogrammedCellType version should be incremented and the reference to cellType within it should be incremented. The downsides to trying to keep two terms in sync...

**Comment by cw-dvr8** [comment]
@Aryllen Looks like there's a problem.  Since cellType v5 doesn't yet exist, reprogrammedCellType is failing.  Without the updated reprogrammedCellType, the PR won't pass.

**Review by Aryllen — APPROVED** [review]
@cw-dvr8, ugh, I forgot that attempting to register the schemas would fail because they are both being updated at the same time. 🤦🏻 It's passing the check to see that they are valid, in general (not on Synapse). Going to approve/merge!

**Pull request merged**
