### PR TITLE
Add behavioral assays

### PR DESCRIPTION
**Pull request by karawoo**
("contextual conditioning behavior" has no description on the term page)

### CODE REVIEW

**Comment by sgosline** [comment]
@milen-sage do any of these correspond with the piggy tests?

**Comment by sgosline** [comment]
otherwise it looks good from the NTAP perspective.

**Comment by karawoo** [comment]
No she didn't

**Comment by milen-sage** [comment]
> @milen-sage do any of these correspond with the piggy tests?
The anxiety-related behavior is related to the piggy tests. And @sgosline you are right that overall that would be a good category to accommodate the pig-characteristics tests for composite pain scores. I can add the piggy assays to this category (they are not really pig specific in terms of keys).

**Comment by amapeters** [comment]
There is a definition in Ontobee, which is the source we have used for the other behavioral assays: http://www.ontobee.org/ontology/NBO?iri=http://purl.obolibrary.org/obo/NBO_0000223

**Comment by karawoo** [comment]
? that is the source I used, and I don't see a description on that page

**Comment by karawoo** [comment]
Summarizing in-person conversation with @amapeters: only contextual conditioning behavior is missing a description, the others each have one, and we should try to keep using this neuro behavior ontology for consistency with previous behavioral assays. Based on this I think this PR should be approved unless anyone else has specific concerns.

**Pull request merged**
