### PR TITLE
added values narrowPeak, broadPeak, and gappedPeak to fileFormat key

### PR DESCRIPTION
**Pull request by ychae**

### CODE REVIEW

**Comment by kdaily** [comment]
See this example as 'bed' as a prefix in ENCODE data matrix:

https://www.encodeproject.org/matrix/?type=Experiment&status=released&award.project=ENCODE&files.file_type=bed+narrowPeak

**Comment by kdaily** [comment]
@amapeters is that OK?

**Comment by kdaily** [comment]
@kkdang the prefixes didn't make it in, though? Might want to revert and restore this PR before?

**Comment by kkdang** [comment]
rats, yes, I need to do that

**Pull request merged**
