### PR TITLE
Add postmortem to clinical

### PR DESCRIPTION
**Pull request by cw-dvr8**

### CODE REVIEW

**Comment by cw-dvr8** [comment]
I decided that this belonged in experimentalData instead of clinical because it specifically deals with tissue.  Although I suspect the possibility is pretty small, it would in theory be possible in a situation where samples were drawn at intervals (such as a clinical trial) that there could be postmortem and non-postmortem tissue samples.

**Review by Aryllen — APPROVED** [review]
Approving, but this is definitely another case where AD uses a similar term, isPostmortem. This is going to make tracking the dictionary terms specific to a consortium interesting...

**Comment by cw-dvr8** [comment]
I didn't see "isPostmortem".  We don't need this if you've already got something, and yours sounds more descriptive anyway.  What module is it in?

**Comment by Aryllen** [comment]
@cw-dvr8, I'm not sure it's more descriptive (minus the hint that it's boolean by adding 'is'). It's also not in this repo, yet, so it just comes down to opinion of which one we should have, which is subjective.

Our term: isPostMortem
definition: Was the sample was taken postmortem (true/false)?

For our term, I realized I put the capitalization wrong in the first comment. Thinking about it, this term (yours, as well) is not about the individual, but rather the sample/specimen so I would probably put this term in 'experimentalData'.

Ultimately, I think it's going to take some fancy thinking to map similar terms together (other examples like ageDeath versus ageOfDeath) so that the AD data dictionary is relevant for users. I'll give it some thought.

**Comment by cw-dvr8** [comment]
I personally like yours better, so I'm going to make an executive decision and run with it.  To me the name more clearly denotes the answer we're going for, and it's not a major change that's going to throw anyone off.  You also make a good point about the module, so I'll switch that too.

**Comment by Aryllen** [comment]
@cw-dvr8, alrighty. Sounds good. Still approved. Also, thank you for moving it to 'experimentalData'!

**Pull request merged**
