### PR TITLE
Updated group and study information

### PR DESCRIPTION
**Pull request by amapeters**

### CODE REVIEW

**Comment by amapeters** [comment]
@kdaily - can you assign me as a reviewer

**Comment by kdaily** [comment]
@amapeters nope - you can't review your own pull request!

**Comment by amapeters** [comment]
Right, that one originated with me.. Can you approve?

**Comment by kdaily** [comment]
I had reviewed - I thought we discussed changing groups with multiple source URLs to a single URL? If not, can approve.

**Comment by kkdang** [comment]
@amapeters Mette, this one can be merged once the multi-URL institutions are changed to single URLs e.g. to a Synapse page for the group.

**Comment by kdaily** [comment]
Closing per @amapeters - going back to combination of study and grant.

**Pull request closed without merging**
