### PR TITLE
Replace repo contents with JSON schemas

### PR DESCRIPTION
**Pull request by karawoo**
As discussed in the metadata working group meeting on 2020-11-11, this PR replaces the contents of this repo with the JSON Schema terms I presented. Old contents of the repo have been removed or updated accordingly.

In addition:
- I've changed the org name in the schemas to `sage.annotations`. I have *not* registered these schemas yet, as it's possible they will conflict with what @cw-dvr8 has registered (and I'm not sure I have permissions on that org). Cindy: how would you like to handle this? 
- I've added documentation on how to contribute new terms to our `CONTRIBUTING.md` guide.
- I've removed the instructions to make PRs to develop. In my opinion, the git flow process caused unnecessary delays for us in the past. I would like us to merge new terms straight to master and hopefully be able to use them right away. Does anyone object?

### CODE REVIEW

**Comment by karawoo** [comment]
One additional note: I haven't added documentation of the modules yet. I agree we want to document that better in the future, though.

**Comment by cw-dvr8** [comment]
@karawoo I will go ahead and delete the schemas I've registered with that organization name by Monday (11/16).

**Review by cw-dvr8 — APPROVED** [review]

**Comment by cw-dvr8** [comment]
@karawoo I've deleted the schemas I had registered under sage.annotations.

**Review by Aryllen — APPROVED** [review]
> I've removed the instructions to make PRs to develop. In my opinion, the git flow process caused unnecessary delays for us in the past. I would like us to merge new terms straight to master and hopefully be able to use them right away. Does anyone object?

No objections from me on this. My only suggestion is that we have something potentially in place for non-group specific additions where PRs need at least one approval (preferably 2+). For example, if I am adding a new assay, that assay should technically be able to be used by multiple groups. It would be ideal if PRs were checked by multiple people to make sure it was a reasonably generalized assay description. However, if someone is adding a study name for an AD study, then it's less needed for it to be checked over by multiple people (outside of general correct structure). I am concerned about holding up the process of adding terms by having us require 2+ or even 1 review, but given that this is our base set of terms, it makes sense to require feedback.

**Comment by karawoo** [comment]
Thanks for the feedback @Aryllen. Currently the settings on this repo require at least 1 approving review to merge a PR, but administrators on the repo can override that and merge PRs without review. So potentially, for project-specific terms we could say that it is ok for an admin to use their powers to merge if no one reviews in a timely manner.

**Comment by Aryllen** [comment]
@karawoo, that sounds reasonable. I think it's more that it might be good to mention in the process/best practices in the README, similar to how it did before, mostly to encourage reaching out for and giving more reviews. I.e. "Add/update by creating a PR. At least one review is required. It's encouraged to request more than one review before merging for any general terms. Feel free to review open PRs." (obviously written better than that, though.)

**Comment by karawoo** [comment]
Gotcha! I can add some language about this.

**Comment by karawoo** [comment]
@Aryllen on closer inspection there were already some instructions about requesting reviews, but they needed to be updated. I removed some out-of-date stuff and replaced with

> For pull requests, request a review from someone in Github - this can be found under 'Reviewers' on the right side of the screen when viewing a Github issue. At least one review is required for any changes to terms that part of the core vocabulary (i.e. non-project-specific terms); more reviews are even better. Everyone is welcome to review open PRs, even if they were not formally assigned through GitHub.

**Pull request merged**
