### PR TITLE
Create chromosome key

### PR DESCRIPTION
**Pull request by avanlinden**
This creates a term for annotating with chromosome number. Format is an enumerated string, with values "1", "2", ... "22" + "X" and "Y". This can be updated if/when we get data from other species with different chromosome numbers and different sex chromosomes. 

I used "Sage Bionetworks" for the source for all values since chromosome number is pretty self-explanatory, but can change this if needed. 

Also open to making the values "chr1", "chr2", etc if that's more in line with what is typically used.

### CODE REVIEW

**Review by Aryllen — APPROVED** [review]
Looks fine to me!

**Comment by cw-dvr8** [comment]
@avanlinden @Aryllen There is already a "sexChromosome" key in the PEC individual manifest.  Is this key something different?

**Comment by Aryllen** [comment]
@cw-dvr8, this is for designating one specific chromosome (not sex). An example would be vcf files; it would be handy to specify which chromosome the data in the file is for.

**Comment by avanlinden** [comment]
@cw-dvr8 Nicole beat me to it but that's exactly it; I think the PEC sexChromosome key is a more specific way of saying the genetically-determined sex of an individual, right? Whereas this is to let us query for data files that belong to specific chromosomes in WGS and genotype data.

**Review by cw-dvr8 — APPROVED** [review]
Thanks for the clarification!  Looks good to me.

**Pull request merged**
